title: journeytocloud
email: journeytocloud@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This project is a showcase of how to setup a portfolio website using GitHub Pages, 
  with the main accent put on the blogging part.
baseurl: '/journeytocloud/docs' # the subpath of your site, e.g. /blog
url: 'https://imm-bak.github.io' # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: imm-bak

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

# Build settings
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

